spring.datasource.url=jdbc:postgresql://ep-jolly-dream-ap7ti2rg-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KqtyBs20nHcp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081